/*
 * The MIT License
 *
 * Copyright 2015 https://github.com/SirJacob
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.github.sirjacob.HumanBody;

import java.util.Scanner;

/**
 *
 * @author https://github.com/SirJacob
 */
public class Display extends javax.swing.JFrame {

    protected Body body;

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
        Scanner s = new Scanner(System.in);
        System.out.println("Use defaults? (Y/N)");
        String answer = s.next();
        if (null != answer) {
            switch (answer) {
                case "Y":
                    body = new Body();
                    setTitle("Defaults were used at start!");
                    break;
                case "N":
                    System.out.println("Display Opened, insert values.");
                    break;
                default:
                    System.exit(0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtArmWeight = new javax.swing.JTextField();
        txtArmStrength = new javax.swing.JTextField();
        toggleArmRBroken = new javax.swing.JToggleButton();
        toggleArmLBroken = new javax.swing.JToggleButton();
        toggleLegRBroken = new javax.swing.JToggleButton();
        toggleLegLBroken = new javax.swing.JToggleButton();
        txtLegStrength = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLegWeight = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPrintInfo = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtLegHeight = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        toggleFemale = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTorsoWeight = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTorsoHeight = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHeadWeight = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtHeadHeight = new javax.swing.JTextField();
        txtTorsoStrength = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnTHeight = new javax.swing.JButton();
        btnTWeight = new javax.swing.JButton();
        btnTStrength = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Arm:");

        jLabel2.setText("Weight:");

        jLabel3.setText("Strength:");

        toggleArmRBroken.setText("Right Broken");
        toggleArmRBroken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleArmRBrokenActionPerformed(evt);
            }
        });

        toggleArmLBroken.setText("Left Broken");
        toggleArmLBroken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleArmLBrokenActionPerformed(evt);
            }
        });

        toggleLegRBroken.setText("Right Broken");
        toggleLegRBroken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleLegRBrokenActionPerformed(evt);
            }
        });

        toggleLegLBroken.setText("Left Broken");
        toggleLegLBroken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleLegLBrokenActionPerformed(evt);
            }
        });

        jLabel4.setText("Strength:");

        jLabel5.setText("Weight:");

        jLabel6.setText("Leg:");

        btnPrintInfo.setText("Print Info");
        btnPrintInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintInfoActionPerformed(evt);
            }
        });

        btnUpdate.setText("Create / Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel7.setText("Height:");

        toggleFemale.setText("isFemale");

        jLabel8.setText("Torso:");

        jLabel9.setText("Weight:");

        jLabel10.setText("Height:");

        jLabel11.setText("Head:");
        jLabel11.setToolTipText("");

        jLabel12.setText("Weight:");

        jLabel13.setText("Height:");

        jLabel14.setText("Strength:");
        jLabel14.setToolTipText("");

        btnTHeight.setText("Get Total Height");
        btnTHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHeightActionPerformed(evt);
            }
        });

        btnTWeight.setText("Get Total Weight");
        btnTWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTWeightActionPerformed(evt);
            }
        });

        btnTStrength.setText("Get Total Strength");
        btnTStrength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTStrengthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArmWeight))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArmStrength, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toggleArmLBroken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleArmRBroken)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLegWeight))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLegStrength))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(toggleLegLBroken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleLegRBroken))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLegHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTorsoWeight))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTorsoStrength, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTorsoHeight)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(286, 286, 286)))
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHeadWeight))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHeadHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toggleFemale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTHeight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTWeight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTStrength)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintInfo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtArmWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtArmStrength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toggleArmLBroken)
                            .addComponent(toggleArmRBroken)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLegWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLegStrength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtLegHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toggleLegLBroken)
                            .addComponent(toggleLegRBroken))))
                .addGap(180, 180, 180)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTorsoWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTorsoHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTorsoStrength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtHeadWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtHeadHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnPrintInfo)
                    .addComponent(btnTStrength)
                    .addComponent(btnTWeight)
                    .addComponent(btnTHeight)
                    .addComponent(toggleFemale)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintInfoActionPerformed
        p(String.format("%s\n%s\n%s\n%s\n%s\n%s\n", body.bp[0].toString(), body.bp[1].toString(), body.bp[2].toString(), body.bp[3].toString(), body.bp[4].toString(), body.bp[5].toString()));
    }//GEN-LAST:event_btnPrintInfoActionPerformed

    private void toggleArmLBrokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleArmLBrokenActionPerformed
        if (toggleArmLBroken.isSelected()) {
            body.bp[3].setBroken(true);
        } else {
            body.bp[3].setBroken(false);
        }
    }//GEN-LAST:event_toggleArmLBrokenActionPerformed

    private void toggleArmRBrokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleArmRBrokenActionPerformed
        if (toggleArmRBroken.isSelected()) {
            body.bp[2].setBroken(true);
        } else {
            body.bp[2].setBroken(false);
        }
    }//GEN-LAST:event_toggleArmRBrokenActionPerformed

    private void toggleLegLBrokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleLegLBrokenActionPerformed
        if (toggleLegLBroken.isSelected()) {
            body.bp[5].setBroken(true);
        } else {
            body.bp[5].setBroken(false);
        }
    }//GEN-LAST:event_toggleLegLBrokenActionPerformed

    private void toggleLegRBrokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleLegRBrokenActionPerformed
        if (toggleLegRBroken.isSelected()) {
            body.bp[4].setBroken(true);
        } else {
            body.bp[4].setBroken(false);
        }
    }//GEN-LAST:event_toggleLegRBrokenActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        body = new Body(toggleFemale.isSelected(),
                Double.parseDouble(txtHeadWeight.getText()), Double.parseDouble(txtHeadHeight.getText()),
                Double.parseDouble(txtTorsoWeight.getText()), Double.parseDouble(txtTorsoHeight.getText()), Double.parseDouble(txtTorsoStrength.getText()),
                Double.parseDouble(txtArmWeight.getText()), Double.parseDouble(txtArmStrength.getText()), toggleArmRBroken.isSelected(), toggleArmLBroken.isSelected(),
                Double.parseDouble(txtLegWeight.getText()), Double.parseDouble(txtLegStrength.getText()), Double.parseDouble(txtLegHeight.getText()), toggleLegRBroken.isSelected(), toggleLegLBroken.isSelected());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHeightActionPerformed
        p("Total Height of Body: " + body.getHeight());
    }//GEN-LAST:event_btnTHeightActionPerformed

    private void btnTWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTWeightActionPerformed
        p("Total Weight of Body: " + body.getWeight());
    }//GEN-LAST:event_btnTWeightActionPerformed

    private void btnTStrengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTStrengthActionPerformed
        p("Total Strength of Body: " + body.getStrength());
    }//GEN-LAST:event_btnTStrengthActionPerformed

    public static void p(String print) {
        System.out.println(print);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Display().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintInfo;
    private javax.swing.JButton btnTHeight;
    private javax.swing.JButton btnTStrength;
    private javax.swing.JButton btnTWeight;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton toggleArmLBroken;
    private javax.swing.JToggleButton toggleArmRBroken;
    private javax.swing.JToggleButton toggleFemale;
    private javax.swing.JToggleButton toggleLegLBroken;
    private javax.swing.JToggleButton toggleLegRBroken;
    private javax.swing.JTextField txtArmStrength;
    private javax.swing.JTextField txtArmWeight;
    private javax.swing.JTextField txtHeadHeight;
    private javax.swing.JTextField txtHeadWeight;
    private javax.swing.JTextField txtLegHeight;
    private javax.swing.JTextField txtLegStrength;
    private javax.swing.JTextField txtLegWeight;
    private javax.swing.JTextField txtTorsoHeight;
    private javax.swing.JTextField txtTorsoStrength;
    private javax.swing.JTextField txtTorsoWeight;
    // End of variables declaration//GEN-END:variables
}
